"""seasons

Revision ID: 460d1b843bcf
Revises: 17f40e419123
Create Date: 2021-08-31 02:38:21.501715

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '460d1b843bcf'
down_revision = '17f40e419123'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('seasons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('season', sa.Integer(), nullable=True),
    sa.Column('next_switch_date', sa.DateTime(), nullable=True),
    sa.Column('ctime', sa.DateTime(), nullable=False),
    sa.Column('etime', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('seasons')
    # ### end Alembic commands ###
