"""users to players table

Revision ID: e6d44eeda171
Revises: 460d1b843bcf
Create Date: 2022-01-05 14:58:54.502580

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e6d44eeda171'
down_revision = '460d1b843bcf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('users_battletag_key', 'users', type_='unique')
    op.drop_constraint('users_username_key', 'users', type_='unique')
    op.drop_constraint('comp_stats_user_id_fkey', 'comp_stats', type_='foreignkey')
    op.rename_table('users', 'players')
    op.alter_column('comp_stats', 'user_id', nullable=False, new_column_name='player_id')
    op.create_foreign_key('comp_stats_player_id_fkey', 'comp_stats', 'players', ['player_id'], ['id'])
    op.execute("ALTER SEQUENCE users_id_seq RENAME TO players_id_seq")
    op.execute("ALTER INDEX users_pkey RENAME TO players_pkey")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER INDEX players_pkey RENAME TO users_pkey")
    op.execute("ALTER SEQUENCE players_id_seq RENAME TO users_id_seq")
    op.rename_table('players', 'users')

    op.drop_constraint('comp_stats_player_id_fkey', 'comp_stats', type_='foreignkey')
    op.alter_column('comp_stats', 'player_id', nullable=False, new_column_name='user_id')
    op.create_foreign_key('comp_stats_user_id_fkey', 'comp_stats', 'users', ['user_id'], ['id'])
    op.create_unique_constraint('users_username_key', 'users', ['username'])
    op.create_unique_constraint('users_battletag_key', 'users', ['battletag'])
    # ### end Alembic commands ###
